[project]
name = "pydle"
version = "0.1.0"
description = "cli wordle"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "configparser>=7.2.0",
    "pipreqs>=0.5.0",
    "prompt-toolkit>=3.0.51",
    "pyinstaller>=6.14.2",
    "regex>=2024.11.6",
]
